// generated by bootstrap4c4d for c4d version 2.0.1
CONTAINER Tposereader
{
    NAME Tposereader;
    INCLUDE Tbase;
    INCLUDE Texpression;
    GROUP GROUP_SETTINGS
    {
        DEFAULT 1;
        BOOL SETTINGS_DRAW_DEBUG_LINES
        {
            ANIM OFF;
        }
        LINK SETTINGS_ORIGIN_OBJECT
        {
            ANIM OFF;
            ACCEPT
            {
                Obase;
            }
        }
        LINK SETTINGS_TARGET_OBJECT
        {
            ANIM OFF;
            ACCEPT
            {
                Obase;
            }
        }
    }
    GROUP GROUP_RESULT
    {
        DEFAULT 1;
        REAL RESULT_ROTATION
        {
            ANIM OFF;
            UNIT DEGREE;
        }
    }
}