// generated by bootstrap4c4d for c4d version 2.0.1
#ifndef _Oatom_H_
#define _Oatom_H_

enum
{
    Tposereader = 20489668,
    GROUP_SETTINGS = 45274978,
    SETTINGS_DRAW_DEBUG_LINES = 43530105,
    SETTINGS_ORIGIN_OBJECT = 73502788,
    SETTINGS_TARGET_OBJECT = 49481569,
    GROUP_RESULT = 4650763,
    RESULT_ROTATION = 75897435,
};

#endif